name: CI

on:
  push:
  schedule:
  - cron: '0 23 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ '18.x', 'latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: node --version
    - run: npm install
    - run: npm list
    - run: npm test
      env:
        NODE_OPTIONS: "--experimental-vm-modules"

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./run-docker-test.sh
