name: CI

on:
  push:
  schedule:
  - cron: '0 23 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ '14.x', '19.x' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm test

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./run-docker-test.sh
